import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import sun.audio.*;
public class MathGame extends javax.swing.JFrame {

    
    public static int players = 0;
    private static int n1, n2=0;
    private static char operator='\0';
    public static List<GameRecord> userList = new ArrayList<GameRecord>();
    public static GameRecord user = null;
    public static RandomQuestion rq= RandomQuestion.getrandom();
    int result = 0;
    public MathGame() {
        initComponents();
        loadGameRecords();
        updateFields();
        generateQuestion();
        /*try {
            playSound();
        } catch (IOException ex) {
            Logger.getLogger(MathGame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Answer = new javax.swing.JButton();
        New = new javax.swing.JButton();
        num2 = new javax.swing.JLabel();
        sign = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        score = new javax.swing.JLabel();
        balance1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        answerTest = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        questions = new javax.swing.JLabel();
        highscore = new javax.swing.JButton();
        myImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Answer.setText("Answer");
        Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerActionPerformed(evt);
            }
        });

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        sign.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        num1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        balance1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        balance1.setText("Score :");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        username2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username2.setText("Active User :");

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        username3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username3.setText("Questions Left :");

        questions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        highscore.setText("High Score");
        highscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreActionPerformed(evt);
            }
        });

        myImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/math.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(highscore, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(balance1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(username3)
                                    .addGap(1, 1, 1)
                                    .addComponent(questions, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(answerTest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myImage)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(highscore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(answerTest, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(myImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questions, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerActionPerformed

        //calculate

        char checkOperator = sign.getText().charAt(0);
        System.out.println(checkOperator);
        n1 = Integer.parseInt(num1.getText());
        n2 = Integer.parseInt(num2.getText());

        double resultDouble = 0.0;

        if(answerTest.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Must input answer!!!");
        }
        else{
            int userAnswer = Integer.parseInt(answerTest.getText());
            switch(checkOperator){

                case '-':
                result =subtration(n1, n2);

                if(result == userAnswer){

                    user.CorrectAns();

                }
                else{
                    user.IncorrectAns();
                }
                updateFields();
                break;

                case '+':
                result =addition(n1, n2);
                System.out.println("R: " + result + " U : " + userAnswer);
                if(result == userAnswer){

                    user.CorrectAns();

                }
                else{
                    user.IncorrectAns();
                }
                updateFields();
                break;

                case '*':
                result =multiplication(n1, n2);

                if(result == userAnswer){

                    user.CorrectAns();

                }
                else{
                    user.IncorrectAns();
                }
                updateFields();
                break;

                case '/':
                resultDouble =division(n1, n2);
                double userAnswerDouble = Double.parseDouble(answerTest.getText());
                if(resultDouble == userAnswerDouble){

                    user.CorrectAns();

                }
                else{
                    user.IncorrectAns();
                }

                break;

            }
            updateFields();
            answerTest.setText("");
            generateQuestion();
        }

    }//GEN-LAST:event_AnswerActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed

        generateQuestion();

    }//GEN-LAST:event_NewActionPerformed

    private void highscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreActionPerformed
     
         HighScore hs = new HighScore();
         
         hs.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_highscoreActionPerformed

   
    public int addition(int a, int b) {
        
        return a+b;
    }

   
    public int subtration(int a, int b) {
        
        return a-b;
    }

   
    public int multiplication(int a, int b) {
       
        return a*b;
    }

    
    public double division(int a, int b) {
       double div = 0.0;
       
       div = a/b;
       
       return div;
    }
         public static void restart(){
      
        
         user.reset();
}
          public static void generateQuestion(){
         Random random = new Random();
        n1 = rq.getNum1();
        n2 = rq.getNum2();
        
        operator= rq.getOperator();
        if(operator == '-' && n1 < n2){
            
           
            num1.setText(Integer.toString(n2));
            num2.setText(Integer.toString(n1));
        }
        else{
            
            num1.setText(Integer.toString(n1));
            num2.setText(Integer.toString(n2));
        }
        
        sign.setText(Character.toString(operator));
         
     }
          
           public static void updateFields(){
        
 
        questions.setText(Integer.toString(user.getQuestions()));
        
     
        
        if(user.getQuestions() == 0){
            
            gameOver();
            int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Play again ?");
            if(dialogResult == JOptionPane.YES_OPTION){
                 userList.add(user);
                try {
                    insertRecords();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MathGame.class.getName()).log(Level.SEVERE, null, ex);
                }
                  loadGameRecords();
                   restart();
                  
                  
                  
                  
              }
            else{
                System.exit(0);
            }
        }
        
        
        score.setText(Integer.toString(user.getScore()));
        
        
    }
     public static void gameOver(){
         
         JOptionPane optionPane = new JOptionPane("Game is over", JOptionPane.ERROR_MESSAGE);    
         JDialog dialog = optionPane.createDialog("Game Over");
         dialog.setAlwaysOnTop(true);
         dialog.setVisible(true);
     }
      public static void loadGameRecords(){
        
       
        String name = JOptionPane.showInputDialog("Enter your Name ");
        user = new GameRecord();
        
        user.setName(name);
       
        username.setText(name);
     }
    
      public static void insertRecords() throws FileNotFoundException{
          
          File file = new File("score.txt");
          //BufferedReader br = new BufferedReader(new FileReader(file));
          PrintWriter pw = new PrintWriter(file);
          
          for(GameRecord list : userList){
              
              pw.write(list.toString()+"\n");
          }
          pw.close();
          
          
      }
      
      public void playSound() throws IOException{
          
        /*String bip = "music.mp3";
        Media hit = new Media("file:///C:/Users/MALIK/Documents/NetBeansProjects/MathLearningGame/src/sound/music.mp3");
        MediaPlayer mediaPlayer = new MediaPlayer(hit);
        mediaPlayer.play();*/
    
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Answer;
    private javax.swing.JButton New;
    private javax.swing.JTextField answerTest;
    private javax.swing.JLabel balance1;
    private javax.swing.JButton highscore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel myImage;
    private static javax.swing.JLabel num1;
    private static javax.swing.JLabel num2;
    private static javax.swing.JLabel questions;
    private static javax.swing.JLabel score;
    private static javax.swing.JLabel sign;
    private static javax.swing.JLabel username;
    private static javax.swing.JLabel username2;
    private static javax.swing.JLabel username3;
    // End of variables declaration//GEN-END:variables
}
